spring:
  application:
    name: baodientu

  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${TMDT_DB_URL} # update to ssl later to secure
    username: ${TMDT_DB_USERNAME}
    password: ${TMDT_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
logging:
  level:
    org.springframework.security: DEBUG

app:
  jwt:
    secret: ${TMDT_JWT_SECRET}
    expiration: 86400000