name: Check Compile

on:
  push:
    branches: [ "main", "develop", "feature/**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup JDK 25
      - name: Setup JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      # 3. Cache Maven (tăng tốc)
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}

      # 4. Compile project
      - name: Compile
        run: mvn -B clean compile